version: "3.7"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - "3000:80"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "4000:4000"